[project]
name = "papers-from-scratch"
version = "0.1.0"
description = "Replication of SOTA AI Models from Scratch Using PyTorch"
authors = [
    {name = "Samyamoy Rakshit", email = "samyamoyrakshit@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "annotated-types==0.7.0",
    "appnope==0.1.4",
    "asttokens==3.0.1",
    "certifi==2025.11.12",
    "charset-normalizer==3.4.4",
    "comm==0.2.3",
    "contourpy==1.3.3",
    "cycler==0.12.1",
    "debugpy==1.8.17",
    "decorator==5.2.1",
    "executing==2.2.1",
    "filelock==3.20.0",
    "fonttools==4.60.1",
    "fsspec==2025.10.0",
    "idna==3.11",
    "ipykernel==6.29.5",
    "ipython==9.3.0",
    "ipython-pygments-lexers==1.1.1",
    "ipywidgets==8.1.7",
    "isort>=7.0.0",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "jupyter-client==8.6.3",
    "jupyter-core==5.9.1",
    "jupyterlab-widgets==3.0.15",
    "kiwisolver==1.4.9",
    "markupsafe==3.0.3",
    "matplotlib==3.10.3",
    "matplotlib-inline==0.2.1",
    "mpmath==1.3.0",
    "nest-asyncio==1.6.0",
    "networkx==3.5",
    "numpy==2.3.1",
    "packaging==25.0",
    "parso==0.8.5",
    "pexpect==4.9.0",
    "pillow==12.0.0",
    "platformdirs==4.5.0",
    "prompt-toolkit==3.0.52",
    "psutil==7.1.3",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.3",
    "pydantic==2.12.4",
    "pydantic-core==2.41.5",
    "pygments==2.19.2",
    "pyparsing==3.2.5",
    "python-dateutil==2.9.0.post0",
    "pyzmq==27.1.0",
    "requests==2.32.4",
    "setuptools==80.9.0",
    "six==1.17.0",
    "stack-data==0.6.3",
    "sympy==1.14.0",
    "torch>=2.12",
    "torchinfo==1.8.0",
    "torchvision>=0.22",
    "tornado==6.5.2",
    "tqdm==4.67.1",
    "traitlets==5.14.3",
    "tree2fs==0.1.0",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "urllib3==2.5.0",
    "wcwidth==0.2.14",
    "widgetsnbextension==4.0.14",
    "sentencepiece>=0.2.0",
    "datasets>=2.14.0",
    "sacrebleu>=2.4.0",
    "pyyaml>=6.0",
    "tensorboard>=2.20.0",
    "python-dotenv>=1.2.2",
    "gradio>=6.15.2",
    "tokenizers>=0.23.1",
]
readme = { file = "README.md", content-type = "text/markdown" }

license = { text = "MIT" } 
keywords = ["pytorch", "deep-learning"]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: MacOS",
  "Operating System :: POSIX :: Linux"
]
